apiVersion: v1
kind: ConfigMap
metadata:
  name: ran-slicing-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app: oai-gnb-slicing
data:
  rrmPolicy.json: |
{{ .Files.Get "configs/rrmPolicy.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gnb-slicing-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: oai-gnb-slicing
data:
  gnb.conf: |
{{ .Files.Get "configs/gnb-slicing.conf" | indent 4 }}
