apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"oranslice-gnb"},"name":"oranslice-gnb","namespace":"nexslice"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"oranslice-gnb"}},"template":{"metadata":{"labels":{"app":"oranslice-gnb"}},"spec":{"containers":[{"args":["echo \"=== Démarrage ORANSlice gNB en mode RFsimulator SERVEUR ===\"\ncd /oai-ran/cmake_targets/ran_build/build\n./nr-softmodem -O /oai-ran/etc/gnb.conf \\\n  --rfsim \\\n  --sa \\\n  -E \\\n  --rfsimulator.serveraddr server \\\n  --gNBs.[0].min_rxtxtime 6 \\\n  2\u003e\u00261\n"],"command":["/bin/bash","-c"],"image":"docker.io/library/oranslice-gnb:latest","imagePullPolicy":"Never","name":"oranslice-gnb","ports":[{"containerPort":38412,"protocol":"SCTP"},{"containerPort":2152,"protocol":"UDP"},{"containerPort":4043,"name":"rfsim","protocol":"TCP"}],"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/oai-ran/etc/gnb.conf","name":"gnb-config","subPath":"gnb-k3s.yaml"},{"mountPath":"/oai-ran/etc/rrmPolicy.json","name":"gnb-config","subPath":"rrmPolicy.json"}]}],"volumes":[{"configMap":{"name":"oranslice-gnb-config"},"name":"gnb-config"}]}}}}
  creationTimestamp: "2025-11-29T17:17:23Z"
  generation: 2
  labels:
    app: oranslice-gnb
  name: oranslice-gnb
  namespace: nexslice
  resourceVersion: "67447"
  uid: 2e810603-9cf2-4d04-8ec8-13db9b8e155b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oranslice-gnb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oranslice-gnb
    spec:
      containers:
      - args:
        - |
          echo "=== Démarrage ORANSlice gNB en mode RFsimulator SERVEUR ==="
          cd /oai-ran/cmake_targets/ran_build/build
          ./nr-softmodem -O /oai-ran/etc/gnb.conf \
            --rfsim \
            --sa \
            -E \
            --rfsimulator.serveraddr server \
            --gNBs.[0].min_rxtxtime 6 \
            2>&1
        command:
        - /bin/bash
        - -c
        image: docker.io/library/oranslice-gnb:latest
        imagePullPolicy: Never
        name: oranslice-gnb
        ports:
        - containerPort: 38412
          protocol: SCTP
        - containerPort: 2152
          protocol: UDP
        - containerPort: 4043
          name: rfsim
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /oai-ran/etc/gnb.conf
          name: gnb-config
          subPath: gnb-k3s.yaml
        - mountPath: /oai-ran/etc/rrmPolicy.json
          name: gnb-config
          subPath: rrmPolicy.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: oranslice-gnb-config
        name: gnb-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-29T17:17:23Z"
    lastUpdateTime: "2025-11-29T17:21:47Z"
    message: ReplicaSet "oranslice-gnb-6f969c6bdd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-30T09:31:28Z"
    lastUpdateTime: "2025-11-30T09:31:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
