apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"ue-mmtc-oai","namespace":"nexslice"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ue-mmtc-oai"}},"template":{"metadata":{"labels":{"app":"ue-mmtc-oai"}},"spec":{"containers":[{"args":["echo \"=== UE mMTC (SST=3) ===\"\nsleep 60\n/opt/oai-nr-ue/bin/nr-uesoftmodem -O /opt/oai-nr-ue/etc/ue.conf \\\n  --rfsim --rfsimulator.serveraddr oranslice-gnb \\\n  -r 106 --numerology 1 --band 78 -C 3619200000 -E 2\u003e\u00261\n"],"command":["/bin/bash","-c"],"image":"docker.io/oaisoftwarealliance/oai-nr-ue:2025.w18","name":"oai-ue","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/opt/oai-nr-ue/etc/ue.conf","name":"config","subPath":"ue.conf"}]}],"volumes":[{"configMap":{"name":"ue-mmtc-oai-config"},"name":"config"}]}}}}
  creationTimestamp: "2025-11-29T17:34:50Z"
  generation: 4
  name: ue-mmtc-oai
  namespace: nexslice
  resourceVersion: "67498"
  uid: 9abde93c-b145-4e6c-a3f1-874ec3b73442
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ue-mmtc-oai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ue-mmtc-oai
    spec:
      containers:
      - args:
        - |
          echo "=== UE mMTC (SST=3) ==="
          sleep 60
          /opt/oai-nr-ue/bin/nr-uesoftmodem -O /opt/oai-nr-ue/etc/ue.conf \
            --rfsim --rfsimulator.serveraddr oranslice-gnb \
            -r 106 --numerology 1 --band 78 -C 3619200000 -E 2>&1
        command:
        - /bin/bash
        - -c
        image: docker.io/oaisoftwarealliance/oai-nr-ue:2025.w18
        imagePullPolicy: IfNotPresent
        name: oai-ue
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/oai-nr-ue/etc/ue.conf
          name: config
          subPath: ue.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: ue-mmtc-oai-config
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-29T17:34:50Z"
    lastUpdateTime: "2025-11-30T07:21:29Z"
    message: ReplicaSet "ue-mmtc-oai-6b7ff85965" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-30T09:31:59Z"
    lastUpdateTime: "2025-11-30T09:31:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
