---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-embb-config
  namespace: nexslice
data:
  ue.conf: |
    uicc0 = {
      imsi = "208950000000041";
      key = "fec86ba6eb707ed08905757b1bb44b8f";
      opc = "C42449363BBAD02B66D16BC975D77CC1";
      dnn = "oai";
      nssai_sst = 1;
      nssai_sd = 0xFFFFFF;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-urllc-config
  namespace: nexslice
data:
  ue.conf: |
    uicc0 = {
      imsi = "208950000000042";
      key = "fec86ba6eb707ed08905757b1bb44b8f";
      opc = "C42449363BBAD02B66D16BC975D77CC1";
      dnn = "oai";
      nssai_sst = 2;
      nssai_sd = 0xFFFFFF;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-mmtc-config
  namespace: nexslice
data:
  ue.conf: |
    uicc0 = {
      imsi = "208950000000043";
      key = "fec86ba6eb707ed08905757b1bb44b8f";
      opc = "C42449363BBAD02B66D16BC975D77CC1";
      dnn = "oai";
      nssai_sst = 3;
      nssai_sd = 0xFFFFFF;
    }
