apiVersion: apps/v1
kind: Deployment
metadata:
  name: oranslice-gnb
  namespace: nexslice
  labels:
    app: oranslice-gnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oranslice-gnb
  template:
    metadata:
      labels:
        app: oranslice-gnb
    spec:
      containers:
      - name: oranslice-gnb
        image: docker.io/library/oranslice-gnb:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
        workingDir: /oai-ran
        env:
          - name: RFSIMULATOR
            value: "server"
        command:
          - /oai-ran/cmake_targets/ran_build/build/nr-softmodem
          - -O
          - /oai-ran/etc/gnb.conf
          - --sa
          - --rfsim
          - --rfsimulator.serveraddr
          - server
        volumeMounts:
          - name: gnb-config
            mountPath: /oai-ran/etc/gnb.conf
            subPath: gnb-k3s.yaml
          - name: rrmpolicy-config
            mountPath: /oai-ran/etc/rrmPolicy.json
            subPath: rrmPolicy.json
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
      restartPolicy: Always
      volumes:
        - name: gnb-config
          configMap:
            name: gnb-config
        - name: rrmpolicy-config
          configMap:
            name: rrmpolicy-config
